### A simple get request to the test endpoint. No need for login
GET {{url}}/auth/test/


### Create a new user - this one will only get a USER role by default
POST {{url}}/auth/register/

{
    "username": "user",
    "password": "test123"
}

### Login USER role
POST {{url}}/auth/login/

{
    "username": "user",
    "password": "test123"
}

> {%
    client.global.set("jwt_token", response.body.token);
    console.log("JWT Token:", client.global.get("jwt_token"));
%}

### Create a new user - ADMIN role
POST {{url}}/auth/register/

{
    "username": "admin",
    "password": "test123"
}


### Login ADMIN role
POST {{url}}/auth/login/

{
    "username": "admin",
    "password": "test123"
}

> {%
    client.global.set("jwt_token", response.body.token);
    console.log("JWT Token:", client.global.get("jwt_token"));
%}


### Add admin role to user
POST {{url}}/auth/user/addrole/
Accept: application/json
Authorization: Bearer {{jwt_token}}

{
    "role": "ADMIN"
}
Accept: application/json
Authorization: Bearer {{jwt_token}}


###
GET {{url}}/destinations

###

GET {{url}}/destinations/1

###

POST {{url}}/destinations
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "city": "Stuttgart",
  "country": "Germany"
}

###

POST {{url}}/destinations
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "city": "Copenhagen",
  "country": "Denmark"
}

###

PUT {{url}}/destinations/2
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "city": "Tangier",
  "country": "Marocco"
}

###

DELETE {{url}}/destinations/2
Authorization: Bearer {{jwt_token}}


###
GET {{url}}/bookings

###

GET {{url}}/bookings/1

###

POST {{url}}/bookings
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "destinationCity": "Stuttgart",
  "departureDate": "2024-12-03T10:15:30",
  "arrivalDate": "2024-12-04T10:16:30",
  "bookingDate": "2024-02-02",
  "status": "PENDING"
}

###

PUT {{url}}/bookings/1
Content-Type: application/json

{
  "destinationCity": "",
  "departureDate": "2024-12-03T10:15:30",
  "arrivalDate": "2024-12-04T10:16:30",
  "bookingDate": "2024-02-02",
  "status": "PENDING"
}

###

DELETE {{url}}/destinations/2
Authorization: Bearer {{jwt_token}}




###

// Room API

GET {{url}}/rooms

###

GET {{url}}/rooms/1

###

POST {{url}}/rooms/hotel/3
Content-Type: application/json

{
  "roomNumber": 11,
  "roomPrice": 1150,
  "roomType": "SINGLE"
}
